language: ruby
rvm:
  - 2.2.1
addons:
  - postgresql: "9.4"
install:
  - gem install rails
before_script:
  - psql -c "CREATE DATABASE tinkuy_development;"
  - xzcat test2/sample-db.pgsql.xz | psql tinkuy_development
script:
  - rake test
  - ./test2/run-blackbox-test.sh
