language: ruby
rvm:
  - 2.2.1
addons:
  - postgresql: "9.4"
before_script:
  - createdb tinkuy_development
  - xzcat test2/sample-db.pgsql.xz | psql tinkuy_development
  - gem install rails
script:
  - rails server && curl http://localhost:3000/
  - # rake test
  - #./test2/run-blackbox-test.sh
